### ISSUE TITLE
Fix dialog styling.

### ISSUE THREAD

**Issue by tscv11** [tscv11/leo4sqlite#1]
Streamline styling for dialogs, hopefully resulting in a smaller script.

**This will be 'shelved' for now. Suggested changes don't appear to work.**

For example, changing QInputDialog.setStylesheet... to self.setStylesheet...etc.
results in this:

_TypeError: setStyleSheet(self, str): argument 1 has unexpected type 'InputDialogs'_

Other times, when the script has actually run the correct styling hasn't been applied.
I may have misinterpreted something, (probably) about how to to properly make the
suggested changes.

**Comment by tbnorth** [comment]
Try

```python
self.setStylesheet(str)
```

without the `self` parameter.

**Comment by tscv11** [comment]
**This has been resolved** - Thank you tbnorth!
