### ISSUE TITLE
Make sure other major platforms are supported.

### ISSUE THREAD

**Issue by tscv11** [tscv11/leo4sqlite#10]
I wonder if there are other file system types I should include. I'll definitely do the above for starters, at least.

**Comment by tscv11** [comment]
Thanks to everyone who didn't embarrass me by pointing out that windows can use forward slashes in paths. Seems like the drive letter would still need to be handled for windows but I'm not sure - time for more reading!

**Comment by tscv11** [comment]
And now I know: windows drives/partitions are mounted the linux way when accessed via linux - unless I'm mistaken no extra handling will be necessary.

**Comment by tscv11** [comment]
I think I jumped the gun (a bad habit): what about Windows or Mac users running Leo? I have to do more research and make sure I know how things work on those platforms. Time for more reading!

**Comment by tscv11** [comment]
Apple uses proprietary hardware as I recall, so making the script work there could be impossible or too involved. Windows will accept forward _or_ backslashes, so nothing needs to be done about that. I'm closing this now and anyone can ask me to open it again if they disagree with my decision.

 tscv11

**Comment by tbnorth** [comment]
I think you're good here.  I'm not very familiar with Macs. but I think the current OS is actually a Linux or at least Unix derivative, so whatever works on linux will probably work there.  Windows apps. and shell commands require backslashes, but Python on Windows treats / as \.
