### ISSUE TITLE
Add setting: when viewing blob, auto-zoom?

### ISSUE THREAD

**Issue by tscv11** [tscv11/leo4sqlite#5]
Another proposed setting.

**Comment by tscv11** [comment]
I've decided to leave zoom alone unless anyone protests- since the render pane remembers its dimensions the user can set it whenever they like and it will stay that way unless they change it again.

**Comment by tbnorth** [comment]
Agree that this is not needed.

**Comment by tscv11** [comment]
That's settled, then.
