### ISSUE TITLE
Exception subclasses

### ISSUE THREAD

**Issue by tbnorth** [tscv11/leo4sqlite#9]
The use of exceptions for aborting the code and reporting the reason is good, very Pythonic. `InputDialogs.__init__` could be made a bit tidier by making all the exceptions a subclass of one class.  So your Exception classes:
```python
class Leo4SqliteError(Exception): pass
class Sqlite3DatabaseError(Leo4SqliteError):
    """File is encrypted or is not a database."""
class NoTempDirectory(Leo4SqliteError):
    """No temp directory specified in settings."""
```
etc.  Then in `InputDialogs.__init__`:
```python
try:
    self.initUI(c)
except Leo4SqliteError as l4serr:
    g.es("\nleo4sqlite plugin: %s\n" % l4serr.__doc__)  
    return
```
Other code remains the same, i.e. you `raise UserCancel()` etc., they're subclasses of `Leo4SqliteError`.

**Comment by tscv11** [comment]
Done.
